### PR TITLE
Feature/central office stairs

### PR DESCRIPTION
**Pull request by priegger**
~Needs testing.~

Works for me, and it's a little nicer like this.

### CODE REVIEW

**Comment by Incand** [comment]
Now you can get from the central office to the hub but not the other direction, right? Is that wanted behavior? Do we need an additional portal in the cloud hub? Why do we even need the central office and not just but conference rooms on the cloud-hub itself?

**Review by Incand — COMMENTED** [review]
Now you can get from the central office to the hub, right? Also:
- is the other direction from the cloud hub to the central office explicitly not wanted?
- Do we need an additional portal in the cloud hub?
- Why do we even need the central office and not just but conference rooms on the cloud-hub itself?

**Comment by priegger** [comment]
You can always go to a branch map and follow the path there. But it's not perfect yet, I know...

**Comment by Incand** [comment]
@priegger Could you remind me again please, why we even need it?

**Comment by priegger** [comment]
> @priegger Could you remind me again please, why we even need it?

Right now, it's just a reachable map with a dead end. So it's just a small change "for fun". ;-)

**Comment by Incand** [comment]
Alright then! Approved.

**Review by Incand — APPROVED** [review]

**Pull request merged**
